filebeat.prospectors:
- type: log
  paths:
    - /var/log/elk-herder/filebeat-watches-me.log
  multiline.pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}'
  multiline.negate: true
  multiline.match: after
output.logstash:
  hosts: ["logstash:5044"]
queue.mem:
   flush.min_events: 0
   flush.timeout: 0s
